package entities;
// Generated 21-mag-2018 10.34.56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Utente generated by hbm2java
 */
public class Utente  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String cf;
     private String nome;
     private String cognome;
     private Date datanascita;
     private String password;
     private String sale;
     private Date datacreazione;
     private char sesso;
     private int groupid;

    public Utente() {
    }

    public Utente(String email, String cf, String nome, String cognome, Date datanascita, String password, String sale, Date datacreazione, char sesso) {
       this.email = email;
       this.cf = cf;
       this.nome = nome;
       this.cognome = cognome;
       this.datanascita = datanascita;
       this.password = password;
       this.sale = sale;
       this.datacreazione = datacreazione;
       this.sesso = sesso;
       this.groupid = groupid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCf() {
        return this.cf;
    }
    
    public void setCf(String cf) {
        this.cf = cf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public Date getDatanascita() {
        return this.datanascita;
    }
    
    public void setDatanascita(Date datanascita) {
        this.datanascita = datanascita;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSale() {
        return this.sale;
    }
    
    public void setSale(String sale) {
        this.sale = sale;
    }
    public Date getDatacreazione() {
        return this.datacreazione;
    }
    
    public void setDatacreazione(Date datacreazione) {
        this.datacreazione = datacreazione;
    }
    public char getSesso() {
        return this.sesso;
    }
    
    public void setSesso(char sesso) {
        this.sesso = sesso;
    }
    public int getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }




}


